### ISSUE TITLE
Enforcing a more precise typecheck when the client sends messages to the server

### ISSUE THREAD

**Issue by TDupriez** [epfl-lara/Implicit-Web-Programming#3]
Regarding the [function ! of the "Server" object on the client side](https://github.com/epfl-lara/Implicit-Web-Programming/blob/PreparingMigrationToLeonWeb/client/src/main/scala/Server.scala#L146).
It can be called with a MessageToServerExpecting[T](T being a subtype of MessageFromServer) and a callback whose argument is of type U, another subtype of MessageFromServer that is not T. While this is obviously not desired, the compiler does not complain.

I'm wondering whether it would be possible to define this function in a way that it typechecks this, even if it means doing the "PartialFunction and existential type wrapping" inside the body of the ! function.

**Comment by MikaelMayer** [comment]
Here is a solution that prevent wrong type-checking and works with the compiler.

```
case class M(a: Int) extends MessageToServerExpecting[R]
case class R(s: String) extends MessageFromServer

object Server {// Mimick actor-like properties
  def ![T <: MessageFromServer](msg: MessageToServerExpecting[T], callback: PartialFunction[T, Unit]): Unit = {
    Handlers.callbacks += callback.asInstanceOf[PartialFunction[U forSome { type U <: MessageFromServer }, Unit]]
    Main.sendMessage(msg)
  }
}

Server ! (M(1), ({ case data =>
   // Do something with data
}): PartialFunction[GotPermalink, Unit])
```

**Comment by TDupriez** [comment]
I've commited that to the PreaparingMigration branch 97ce29f553a062d3603333ec8f3753b88572435c
